/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Admin: () => import('#controllers/admin_controller'),
  AnalisisIa: () => import('#controllers/analisis_ia_controller'),
  AplicacionesTratamientos: () => import('#controllers/aplicaciones_tratamientos_controller'),
  Auth: () => import('#controllers/auth_controller'),
  Cafeteros: () => import('#controllers/cafeteros_controller'),
  CatEstadosAnalises: () => import('#controllers/cat_estados_analises_controller'),
  CatEstadosCultivos: () => import('#controllers/cat_estados_cultivos_controller'),
  CatNivelesRoyas: () => import('#controllers/cat_niveles_royas_controller'),
  CatPrioridades: () => import('#controllers/cat_prioridades_controller'),
  CatRoles: () => import('#controllers/cat_roles_controller'),
  CatTiposRecomendacions: () => import('#controllers/cat_tipos_recomendacions_controller'),
  CatTiposTratamientos: () => import('#controllers/cat_tipos_tratamientos_controller'),
  Categorias: () => import('#controllers/categorias_controller'),
  Cultivos: () => import('#controllers/cultivos_controller'),
  Expertos: () => import('#controllers/expertos_controller'),
  Fincas: () => import('#controllers/fincas_controller'),
  Imagenes: () => import('#controllers/imagenes_controller'),
  Monitoreos: () => import('#controllers/monitoreos_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  RecomendacionTratamientos: () => import('#controllers/recomendacion_tratamientos_controller'),
  Recomendaciones: () => import('#controllers/recomendaciones_controller'),
  Roles: () => import('#controllers/roles_controller'),
  Tratamientos: () => import('#controllers/tratamientos_controller'),
  Usuarios: () => import('#controllers/usuarios_controller'),
}
