/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = [
    'abilities',
    'createdAt',
    'expiresAt',
    'hash',
    'id',
    'lastUsedAt',
    'name',
    'tokenableId',
    'type',
    'updatedAt',
  ] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CatEstadosAnalisiSchema extends BaseModel {
  static $columns = ['createdAt', 'descripcion', 'idEstado', 'nombreEstado', 'updatedAt'] as const
  $columns = CatEstadosAnalisiSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare descripcion: string | null
  @column({ isPrimary: true })
  declare idEstado: number
  @column()
  declare nombreEstado: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CatEstadosCultivoSchema extends BaseModel {
  static $columns = ['createdAt', 'descripcion', 'idEstado', 'nombreEstado', 'updatedAt'] as const
  $columns = CatEstadosCultivoSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare descripcion: string | null
  @column({ isPrimary: true })
  declare idEstado: number
  @column()
  declare nombreEstado: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CatNivelesRoyaSchema extends BaseModel {
  static $columns = ['createdAt', 'descripcion', 'idNivel', 'nombreNivel', 'updatedAt'] as const
  $columns = CatNivelesRoyaSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare descripcion: string | null
  @column({ isPrimary: true })
  declare idNivel: number
  @column()
  declare nombreNivel: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CatPrioridadeSchema extends BaseModel {
  static $columns = ['createdAt', 'idPrioridad', 'nivelOrden', 'nombre', 'updatedAt'] as const
  $columns = CatPrioridadeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare idPrioridad: number
  @column()
  declare nivelOrden: number | null
  @column()
  declare nombre: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CatRoleSchema extends BaseModel {
  static $columns = ['createdAt', 'descripcion', 'idRol', 'nombreRol', 'updatedAt'] as const
  $columns = CatRoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare descripcion: string | null
  @column({ isPrimary: true })
  declare idRol: number
  @column()
  declare nombreRol: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CatTiposRecomendacionSchema extends BaseModel {
  static $columns = ['createdAt', 'descripcion', 'idTipo', 'nombreTipo', 'updatedAt'] as const
  $columns = CatTiposRecomendacionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare descripcion: string | null
  @column({ isPrimary: true })
  declare idTipo: number
  @column()
  declare nombreTipo: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CatTiposTratamientoSchema extends BaseModel {
  static $columns = ['createdAt', 'descripcion', 'idTipo', 'nombreTipo', 'updatedAt'] as const
  $columns = CatTiposTratamientoSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare descripcion: string | null
  @column({ isPrimary: true })
  declare idTipo: number
  @column()
  declare nombreTipo: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UsuarioSchema extends BaseModel {
  static $columns = [
    'activo',
    'apellido',
    'correo',
    'fechaActualizacion',
    'fechaRegistro',
    'idRol',
    'idUsuario',
    'nombre',
    'observaciones',
    'passwordHash',
    'telefono',
  ] as const
  $columns = UsuarioSchema.$columns
  @column()
  declare activo: boolean | null
  @column()
  declare apellido: string
  @column()
  declare correo: string
  @column.dateTime()
  declare fechaActualizacion: DateTime
  @column.dateTime()
  declare fechaRegistro: DateTime
  @column()
  declare idRol: number | null
  @column({ isPrimary: true })
  declare idUsuario: number
  @column()
  declare nombre: string
  @column()
  declare observaciones: string | null
  @column()
  declare passwordHash: string
  @column()
  declare telefono: string | null
}
