/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AnalisisIaSchema extends BaseModel {
  static $columns = ['fechaActualizacion', 'fechaRegistro', 'idAnalisis', 'idEstado', 'idImagen', 'idNivelRoya', 'porcentajeConfianza', 'resultado'] as const
  $columns = AnalisisIaSchema.$columns
  @column.dateTime()
  declare fechaActualizacion: DateTime | null
  @column.dateTime()
  declare fechaRegistro: DateTime | null
  @column({ isPrimary: true })
  declare idAnalisis: number
  @column()
  declare idEstado: number | null
  @column()
  declare idImagen: number | null
  @column()
  declare idNivelRoya: number | null
  @column()
  declare porcentajeConfianza: string | null
  @column()
  declare resultado: string | null
}

export class AplicacionesTratamientoSchema extends BaseModel {
  static $columns = ['dosis', 'fechaActualizacion', 'fechaRegistro', 'frecuencia', 'idAplicacion', 'idTratamiento', 'idUsuario', 'observaciones'] as const
  $columns = AplicacionesTratamientoSchema.$columns
  @column()
  declare dosis: string
  @column.dateTime()
  declare fechaActualizacion: DateTime
  @column.dateTime()
  declare fechaRegistro: DateTime
  @column()
  declare frecuencia: string | null
  @column({ isPrimary: true })
  declare idAplicacion: number
  @column()
  declare idTratamiento: number | null
  @column()
  declare idUsuario: number | null
  @column()
  declare observaciones: string | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CatEstadosAnalisiSchema extends BaseModel {
  static $columns = ['createdAt', 'descripcion', 'idEstado', 'nombreEstado', 'updatedAt'] as const
  $columns = CatEstadosAnalisiSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare descripcion: string | null
  @column({ isPrimary: true })
  declare idEstado: number
  @column()
  declare nombreEstado: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CatEstadosCultivoSchema extends BaseModel {
  static $columns = ['createdAt', 'descripcion', 'idEstado', 'nombreEstado', 'updatedAt'] as const
  $columns = CatEstadosCultivoSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare descripcion: string | null
  @column({ isPrimary: true })
  declare idEstado: number
  @column()
  declare nombreEstado: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CatNivelesRoyaSchema extends BaseModel {
  static $columns = ['createdAt', 'descripcion', 'idNivel', 'nombreNivel', 'updatedAt'] as const
  $columns = CatNivelesRoyaSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare descripcion: string | null
  @column({ isPrimary: true })
  declare idNivel: number
  @column()
  declare nombreNivel: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CatPrioridadeSchema extends BaseModel {
  static $columns = ['createdAt', 'idPrioridad', 'nivelOrden', 'nombre', 'updatedAt'] as const
  $columns = CatPrioridadeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare idPrioridad: number
  @column()
  declare nivelOrden: number | null
  @column()
  declare nombre: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CatRoleSchema extends BaseModel {
  static $columns = ['createdAt', 'descripcion', 'idRol', 'nombreRol', 'updatedAt'] as const
  $columns = CatRoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare descripcion: string | null
  @column({ isPrimary: true })
  declare idRol: number
  @column()
  declare nombreRol: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CatTiposRecomendacionSchema extends BaseModel {
  static $columns = ['createdAt', 'descripcion', 'idTipo', 'nombreTipo', 'updatedAt'] as const
  $columns = CatTiposRecomendacionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare descripcion: string | null
  @column({ isPrimary: true })
  declare idTipo: number
  @column()
  declare nombreTipo: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CatTiposTratamientoSchema extends BaseModel {
  static $columns = ['createdAt', 'descripcion', 'idTipo', 'nombreTipo', 'updatedAt'] as const
  $columns = CatTiposTratamientoSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare descripcion: string | null
  @column({ isPrimary: true })
  declare idTipo: number
  @column()
  declare nombreTipo: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CultivoSchema extends BaseModel {
  static $columns = ['createdAt', 'idCultivo', 'idEstado', 'idFinca', 'nombreCultivo', 'tipoCultivo', 'updatedAt'] as const
  $columns = CultivoSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare idCultivo: number
  @column()
  declare idEstado: number | null
  @column()
  declare idFinca: number | null
  @column()
  declare nombreCultivo: string
  @column()
  declare tipoCultivo: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class FincaSchema extends BaseModel {
  static $columns = ['altitudMsnm', 'areaHectareas', 'departamento', 'fechaActualizacion', 'fechaRegistro', 'idFinca', 'idUsuario', 'latitud', 'longitud', 'municipio', 'nombreFinca'] as const
  $columns = FincaSchema.$columns
  @column()
  declare altitudMsnm: string | null
  @column()
  declare areaHectareas: string | null
  @column()
  declare departamento: string
  @column.dateTime()
  declare fechaActualizacion: DateTime
  @column.dateTime()
  declare fechaRegistro: DateTime
  @column({ isPrimary: true })
  declare idFinca: number
  @column()
  declare idUsuario: number | null
  @column()
  declare latitud: string | null
  @column()
  declare longitud: string | null
  @column()
  declare municipio: string
  @column()
  declare nombreFinca: string
}

export class ImageneSchema extends BaseModel {
  static $columns = ['fechaActualizacion', 'fechaRegistro', 'idImagen', 'idMonitoreo', 'rutaImagen'] as const
  $columns = ImageneSchema.$columns
  @column.dateTime()
  declare fechaActualizacion: DateTime | null
  @column.dateTime()
  declare fechaRegistro: DateTime | null
  @column({ isPrimary: true })
  declare idImagen: number
  @column()
  declare idMonitoreo: number | null
  @column()
  declare rutaImagen: string
}

export class MonitoreoSchema extends BaseModel {
  static $columns = ['fechaActualizacion', 'fechaMonitoreo', 'fechaRegistro', 'idCultivo', 'idExperto', 'idMonitoreo', 'observaciones'] as const
  $columns = MonitoreoSchema.$columns
  @column.dateTime()
  declare fechaActualizacion: DateTime
  @column.date()
  declare fechaMonitoreo: DateTime
  @column.dateTime()
  declare fechaRegistro: DateTime
  @column()
  declare idCultivo: number | null
  @column()
  declare idExperto: number | null
  @column({ isPrimary: true })
  declare idMonitoreo: number
  @column()
  declare observaciones: string | null
}

export class RecomendacioneSchema extends BaseModel {
  static $columns = ['descripcion', 'fechaActualizacion', 'fechaLimite', 'fechaRegistro', 'idExpertoEmisor', 'idMonitoreo', 'idPrioridad', 'idRecomendacion', 'idTipo'] as const
  $columns = RecomendacioneSchema.$columns
  @column()
  declare descripcion: string | null
  @column.dateTime()
  declare fechaActualizacion: DateTime
  @column.date()
  declare fechaLimite: DateTime | null
  @column.dateTime()
  declare fechaRegistro: DateTime
  @column()
  declare idExpertoEmisor: number | null
  @column()
  declare idMonitoreo: number | null
  @column()
  declare idPrioridad: number | null
  @column({ isPrimary: true })
  declare idRecomendacion: number
  @column()
  declare idTipo: number | null
}

export class RecomendacionTratamientoSchema extends BaseModel {
  static $columns = ['createdAt', 'dosisAjustada', 'idAplicacion', 'idRecTratamiento', 'idRecomendacion', 'notas', 'updatedAt'] as const
  $columns = RecomendacionTratamientoSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare dosisAjustada: string | null
  @column()
  declare idAplicacion: number | null
  @column({ isPrimary: true })
  declare idRecTratamiento: number
  @column()
  declare idRecomendacion: number | null
  @column()
  declare notas: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TratamientoSchema extends BaseModel {
  static $columns = ['descripcion', 'fechaActualizacion', 'fechaRegistro', 'idTipoTratamiento', 'idTratamiento', 'nombre'] as const
  $columns = TratamientoSchema.$columns
  @column()
  declare descripcion: string | null
  @column.dateTime()
  declare fechaActualizacion: DateTime
  @column.dateTime()
  declare fechaRegistro: DateTime
  @column()
  declare idTipoTratamiento: number | null
  @column({ isPrimary: true })
  declare idTratamiento: number
  @column()
  declare nombre: string
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UsuarioSchema extends BaseModel {
  static $columns = ['activo', 'apellido', 'correo', 'fechaActualizacion', 'fechaRegistro', 'idRol', 'idUsuario', 'nombre', 'observaciones', 'passwordHash', 'telefono'] as const
  $columns = UsuarioSchema.$columns
  @column()
  declare activo: boolean | null
  @column()
  declare apellido: string
  @column()
  declare correo: string
  @column.dateTime()
  declare fechaActualizacion: DateTime
  @column.dateTime()
  declare fechaRegistro: DateTime
  @column()
  declare idRol: number | null
  @column({ isPrimary: true })
  declare idUsuario: number
  @column()
  declare nombre: string
  @column()
  declare observaciones: string | null
  @column()
  declare passwordHash: string
  @column()
  declare telefono: string | null
}
