/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'auth.login': {
    methods: ["POST"],
    pattern: '/login',
    tokens: [{"old":"/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['auth.login']['types'],
  },
  'usuarios.index': {
    methods: ["GET","HEAD"],
    pattern: '/usuarios',
    tokens: [{"old":"/usuarios","type":0,"val":"usuarios","end":""}],
    types: placeholder as Registry['usuarios.index']['types'],
  },
  'usuarios.store': {
    methods: ["POST"],
    pattern: '/usuarios',
    tokens: [{"old":"/usuarios","type":0,"val":"usuarios","end":""}],
    types: placeholder as Registry['usuarios.store']['types'],
  },
  'usuarios.show': {
    methods: ["GET","HEAD"],
    pattern: '/usuarios/:id',
    tokens: [{"old":"/usuarios/:id","type":0,"val":"usuarios","end":""},{"old":"/usuarios/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['usuarios.show']['types'],
  },
  'usuarios.update': {
    methods: ["PUT"],
    pattern: '/usuarios/:id',
    tokens: [{"old":"/usuarios/:id","type":0,"val":"usuarios","end":""},{"old":"/usuarios/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['usuarios.update']['types'],
  },
  'usuarios.destroy': {
    methods: ["DELETE"],
    pattern: '/usuarios/:id',
    tokens: [{"old":"/usuarios/:id","type":0,"val":"usuarios","end":""},{"old":"/usuarios/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['usuarios.destroy']['types'],
  },
  'admins.index': {
    methods: ["GET","HEAD"],
    pattern: '/admins',
    tokens: [{"old":"/admins","type":0,"val":"admins","end":""}],
    types: placeholder as Registry['admins.index']['types'],
  },
  'admins.store': {
    methods: ["POST"],
    pattern: '/admins',
    tokens: [{"old":"/admins","type":0,"val":"admins","end":""}],
    types: placeholder as Registry['admins.store']['types'],
  },
  'admins.show': {
    methods: ["GET","HEAD"],
    pattern: '/admins/:id',
    tokens: [{"old":"/admins/:id","type":0,"val":"admins","end":""},{"old":"/admins/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admins.show']['types'],
  },
  'admins.update': {
    methods: ["PUT"],
    pattern: '/admins/:id',
    tokens: [{"old":"/admins/:id","type":0,"val":"admins","end":""},{"old":"/admins/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admins.update']['types'],
  },
  'admins.destroy': {
    methods: ["DELETE"],
    pattern: '/admins/:id',
    tokens: [{"old":"/admins/:id","type":0,"val":"admins","end":""},{"old":"/admins/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admins.destroy']['types'],
  },
  'cafeteros.index': {
    methods: ["GET","HEAD"],
    pattern: '/cafeteros',
    tokens: [{"old":"/cafeteros","type":0,"val":"cafeteros","end":""}],
    types: placeholder as Registry['cafeteros.index']['types'],
  },
  'cafeteros.store': {
    methods: ["POST"],
    pattern: '/cafeteros',
    tokens: [{"old":"/cafeteros","type":0,"val":"cafeteros","end":""}],
    types: placeholder as Registry['cafeteros.store']['types'],
  },
  'cafeteros.show': {
    methods: ["GET","HEAD"],
    pattern: '/cafeteros/:id',
    tokens: [{"old":"/cafeteros/:id","type":0,"val":"cafeteros","end":""},{"old":"/cafeteros/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cafeteros.show']['types'],
  },
  'cafeteros.update': {
    methods: ["PUT"],
    pattern: '/cafeteros/:id',
    tokens: [{"old":"/cafeteros/:id","type":0,"val":"cafeteros","end":""},{"old":"/cafeteros/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cafeteros.update']['types'],
  },
  'cafeteros.destroy': {
    methods: ["DELETE"],
    pattern: '/cafeteros/:id',
    tokens: [{"old":"/cafeteros/:id","type":0,"val":"cafeteros","end":""},{"old":"/cafeteros/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cafeteros.destroy']['types'],
  },
  'expertos.index': {
    methods: ["GET","HEAD"],
    pattern: '/expertos',
    tokens: [{"old":"/expertos","type":0,"val":"expertos","end":""}],
    types: placeholder as Registry['expertos.index']['types'],
  },
  'expertos.store': {
    methods: ["POST"],
    pattern: '/expertos',
    tokens: [{"old":"/expertos","type":0,"val":"expertos","end":""}],
    types: placeholder as Registry['expertos.store']['types'],
  },
  'expertos.show': {
    methods: ["GET","HEAD"],
    pattern: '/expertos/:id',
    tokens: [{"old":"/expertos/:id","type":0,"val":"expertos","end":""},{"old":"/expertos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['expertos.show']['types'],
  },
  'expertos.update': {
    methods: ["PUT"],
    pattern: '/expertos/:id',
    tokens: [{"old":"/expertos/:id","type":0,"val":"expertos","end":""},{"old":"/expertos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['expertos.update']['types'],
  },
  'expertos.destroy': {
    methods: ["DELETE"],
    pattern: '/expertos/:id',
    tokens: [{"old":"/expertos/:id","type":0,"val":"expertos","end":""},{"old":"/expertos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['expertos.destroy']['types'],
  },
  'roles.index': {
    methods: ["GET","HEAD"],
    pattern: '/roles',
    tokens: [{"old":"/roles","type":0,"val":"roles","end":""}],
    types: placeholder as Registry['roles.index']['types'],
  },
  'roles.store': {
    methods: ["POST"],
    pattern: '/roles',
    tokens: [{"old":"/roles","type":0,"val":"roles","end":""}],
    types: placeholder as Registry['roles.store']['types'],
  },
  'roles.show': {
    methods: ["GET","HEAD"],
    pattern: '/roles/:id',
    tokens: [{"old":"/roles/:id","type":0,"val":"roles","end":""},{"old":"/roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['roles.show']['types'],
  },
  'roles.update': {
    methods: ["PUT"],
    pattern: '/roles/:id',
    tokens: [{"old":"/roles/:id","type":0,"val":"roles","end":""},{"old":"/roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['roles.update']['types'],
  },
  'roles.destroy': {
    methods: ["DELETE"],
    pattern: '/roles/:id',
    tokens: [{"old":"/roles/:id","type":0,"val":"roles","end":""},{"old":"/roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['roles.destroy']['types'],
  },
  'cat_roles.index': {
    methods: ["GET","HEAD"],
    pattern: '/cat_roles',
    tokens: [{"old":"/cat_roles","type":0,"val":"cat_roles","end":""}],
    types: placeholder as Registry['cat_roles.index']['types'],
  },
  'cat_roles.store': {
    methods: ["POST"],
    pattern: '/cat_roles',
    tokens: [{"old":"/cat_roles","type":0,"val":"cat_roles","end":""}],
    types: placeholder as Registry['cat_roles.store']['types'],
  },
  'cat_roles.show': {
    methods: ["GET","HEAD"],
    pattern: '/cat_roles/:id',
    tokens: [{"old":"/cat_roles/:id","type":0,"val":"cat_roles","end":""},{"old":"/cat_roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_roles.show']['types'],
  },
  'cat_roles.update': {
    methods: ["PUT"],
    pattern: '/cat_roles/:id',
    tokens: [{"old":"/cat_roles/:id","type":0,"val":"cat_roles","end":""},{"old":"/cat_roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_roles.update']['types'],
  },
  'cat_roles.destroy': {
    methods: ["DELETE"],
    pattern: '/cat_roles/:id',
    tokens: [{"old":"/cat_roles/:id","type":0,"val":"cat_roles","end":""},{"old":"/cat_roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_roles.destroy']['types'],
  },
  'cat_tipos_tratamiento.index': {
    methods: ["GET","HEAD"],
    pattern: '/cat_tipos_tratamiento',
    tokens: [{"old":"/cat_tipos_tratamiento","type":0,"val":"cat_tipos_tratamiento","end":""}],
    types: placeholder as Registry['cat_tipos_tratamiento.index']['types'],
  },
  'cat_tipos_tratamiento.store': {
    methods: ["POST"],
    pattern: '/cat_tipos_tratamiento',
    tokens: [{"old":"/cat_tipos_tratamiento","type":0,"val":"cat_tipos_tratamiento","end":""}],
    types: placeholder as Registry['cat_tipos_tratamiento.store']['types'],
  },
  'cat_tipos_tratamiento.show': {
    methods: ["GET","HEAD"],
    pattern: '/cat_tipos_tratamiento/:id',
    tokens: [{"old":"/cat_tipos_tratamiento/:id","type":0,"val":"cat_tipos_tratamiento","end":""},{"old":"/cat_tipos_tratamiento/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_tipos_tratamiento.show']['types'],
  },
  'cat_tipos_tratamiento.update': {
    methods: ["PUT"],
    pattern: '/cat_tipos_tratamiento/:id',
    tokens: [{"old":"/cat_tipos_tratamiento/:id","type":0,"val":"cat_tipos_tratamiento","end":""},{"old":"/cat_tipos_tratamiento/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_tipos_tratamiento.update']['types'],
  },
  'cat_tipos_tratamiento.destroy': {
    methods: ["DELETE"],
    pattern: '/cat_tipos_tratamiento/:id',
    tokens: [{"old":"/cat_tipos_tratamiento/:id","type":0,"val":"cat_tipos_tratamiento","end":""},{"old":"/cat_tipos_tratamiento/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_tipos_tratamiento.destroy']['types'],
  },
  'cat_niveles_roya.index': {
    methods: ["GET","HEAD"],
    pattern: '/cat_niveles_roya',
    tokens: [{"old":"/cat_niveles_roya","type":0,"val":"cat_niveles_roya","end":""}],
    types: placeholder as Registry['cat_niveles_roya.index']['types'],
  },
  'cat_niveles_roya.store': {
    methods: ["POST"],
    pattern: '/cat_niveles_roya',
    tokens: [{"old":"/cat_niveles_roya","type":0,"val":"cat_niveles_roya","end":""}],
    types: placeholder as Registry['cat_niveles_roya.store']['types'],
  },
  'cat_niveles_roya.show': {
    methods: ["GET","HEAD"],
    pattern: '/cat_niveles_roya/:id',
    tokens: [{"old":"/cat_niveles_roya/:id","type":0,"val":"cat_niveles_roya","end":""},{"old":"/cat_niveles_roya/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_niveles_roya.show']['types'],
  },
  'cat_niveles_roya.update': {
    methods: ["PUT"],
    pattern: '/cat_niveles_roya/:id',
    tokens: [{"old":"/cat_niveles_roya/:id","type":0,"val":"cat_niveles_roya","end":""},{"old":"/cat_niveles_roya/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_niveles_roya.update']['types'],
  },
  'cat_niveles_roya.destroy': {
    methods: ["DELETE"],
    pattern: '/cat_niveles_roya/:id',
    tokens: [{"old":"/cat_niveles_roya/:id","type":0,"val":"cat_niveles_roya","end":""},{"old":"/cat_niveles_roya/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_niveles_roya.destroy']['types'],
  },
  'cat_prioridades.index': {
    methods: ["GET","HEAD"],
    pattern: '/cat_prioridades',
    tokens: [{"old":"/cat_prioridades","type":0,"val":"cat_prioridades","end":""}],
    types: placeholder as Registry['cat_prioridades.index']['types'],
  },
  'cat_prioridades.store': {
    methods: ["POST"],
    pattern: '/cat_prioridades',
    tokens: [{"old":"/cat_prioridades","type":0,"val":"cat_prioridades","end":""}],
    types: placeholder as Registry['cat_prioridades.store']['types'],
  },
  'cat_prioridades.show': {
    methods: ["GET","HEAD"],
    pattern: '/cat_prioridades/:id',
    tokens: [{"old":"/cat_prioridades/:id","type":0,"val":"cat_prioridades","end":""},{"old":"/cat_prioridades/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_prioridades.show']['types'],
  },
  'cat_prioridades.update': {
    methods: ["PUT"],
    pattern: '/cat_prioridades/:id',
    tokens: [{"old":"/cat_prioridades/:id","type":0,"val":"cat_prioridades","end":""},{"old":"/cat_prioridades/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_prioridades.update']['types'],
  },
  'cat_prioridades.destroy': {
    methods: ["DELETE"],
    pattern: '/cat_prioridades/:id',
    tokens: [{"old":"/cat_prioridades/:id","type":0,"val":"cat_prioridades","end":""},{"old":"/cat_prioridades/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_prioridades.destroy']['types'],
  },
  'cat_tipos_recomendacion.index': {
    methods: ["GET","HEAD"],
    pattern: '/cat_tipos_recomendacion',
    tokens: [{"old":"/cat_tipos_recomendacion","type":0,"val":"cat_tipos_recomendacion","end":""}],
    types: placeholder as Registry['cat_tipos_recomendacion.index']['types'],
  },
  'cat_tipos_recomendacion.store': {
    methods: ["POST"],
    pattern: '/cat_tipos_recomendacion',
    tokens: [{"old":"/cat_tipos_recomendacion","type":0,"val":"cat_tipos_recomendacion","end":""}],
    types: placeholder as Registry['cat_tipos_recomendacion.store']['types'],
  },
  'cat_tipos_recomendacion.show': {
    methods: ["GET","HEAD"],
    pattern: '/cat_tipos_recomendacion/:id',
    tokens: [{"old":"/cat_tipos_recomendacion/:id","type":0,"val":"cat_tipos_recomendacion","end":""},{"old":"/cat_tipos_recomendacion/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_tipos_recomendacion.show']['types'],
  },
  'cat_tipos_recomendacion.update': {
    methods: ["PUT"],
    pattern: '/cat_tipos_recomendacion/:id',
    tokens: [{"old":"/cat_tipos_recomendacion/:id","type":0,"val":"cat_tipos_recomendacion","end":""},{"old":"/cat_tipos_recomendacion/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_tipos_recomendacion.update']['types'],
  },
  'cat_tipos_recomendacion.destroy': {
    methods: ["DELETE"],
    pattern: '/cat_tipos_recomendacion/:id',
    tokens: [{"old":"/cat_tipos_recomendacion/:id","type":0,"val":"cat_tipos_recomendacion","end":""},{"old":"/cat_tipos_recomendacion/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_tipos_recomendacion.destroy']['types'],
  },
  'cat_estados_analisis.index': {
    methods: ["GET","HEAD"],
    pattern: '/cat_estados_analisis',
    tokens: [{"old":"/cat_estados_analisis","type":0,"val":"cat_estados_analisis","end":""}],
    types: placeholder as Registry['cat_estados_analisis.index']['types'],
  },
  'cat_estados_analisis.store': {
    methods: ["POST"],
    pattern: '/cat_estados_analisis',
    tokens: [{"old":"/cat_estados_analisis","type":0,"val":"cat_estados_analisis","end":""}],
    types: placeholder as Registry['cat_estados_analisis.store']['types'],
  },
  'cat_estados_analisis.show': {
    methods: ["GET","HEAD"],
    pattern: '/cat_estados_analisis/:id',
    tokens: [{"old":"/cat_estados_analisis/:id","type":0,"val":"cat_estados_analisis","end":""},{"old":"/cat_estados_analisis/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_estados_analisis.show']['types'],
  },
  'cat_estados_analisis.update': {
    methods: ["PUT"],
    pattern: '/cat_estados_analisis/:id',
    tokens: [{"old":"/cat_estados_analisis/:id","type":0,"val":"cat_estados_analisis","end":""},{"old":"/cat_estados_analisis/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_estados_analisis.update']['types'],
  },
  'cat_estados_analisis.destroy': {
    methods: ["DELETE"],
    pattern: '/cat_estados_analisis/:id',
    tokens: [{"old":"/cat_estados_analisis/:id","type":0,"val":"cat_estados_analisis","end":""},{"old":"/cat_estados_analisis/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_estados_analisis.destroy']['types'],
  },
  'cat_estados_cultivo.index': {
    methods: ["GET","HEAD"],
    pattern: '/cat_estados_cultivo',
    tokens: [{"old":"/cat_estados_cultivo","type":0,"val":"cat_estados_cultivo","end":""}],
    types: placeholder as Registry['cat_estados_cultivo.index']['types'],
  },
  'cat_estados_cultivo.store': {
    methods: ["POST"],
    pattern: '/cat_estados_cultivo',
    tokens: [{"old":"/cat_estados_cultivo","type":0,"val":"cat_estados_cultivo","end":""}],
    types: placeholder as Registry['cat_estados_cultivo.store']['types'],
  },
  'cat_estados_cultivo.show': {
    methods: ["GET","HEAD"],
    pattern: '/cat_estados_cultivo/:id',
    tokens: [{"old":"/cat_estados_cultivo/:id","type":0,"val":"cat_estados_cultivo","end":""},{"old":"/cat_estados_cultivo/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_estados_cultivo.show']['types'],
  },
  'cat_estados_cultivo.update': {
    methods: ["PUT"],
    pattern: '/cat_estados_cultivo/:id',
    tokens: [{"old":"/cat_estados_cultivo/:id","type":0,"val":"cat_estados_cultivo","end":""},{"old":"/cat_estados_cultivo/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_estados_cultivo.update']['types'],
  },
  'cat_estados_cultivo.destroy': {
    methods: ["DELETE"],
    pattern: '/cat_estados_cultivo/:id',
    tokens: [{"old":"/cat_estados_cultivo/:id","type":0,"val":"cat_estados_cultivo","end":""},{"old":"/cat_estados_cultivo/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_estados_cultivo.destroy']['types'],
  },
  'categorias.index': {
    methods: ["GET","HEAD"],
    pattern: '/categorias',
    tokens: [{"old":"/categorias","type":0,"val":"categorias","end":""}],
    types: placeholder as Registry['categorias.index']['types'],
  },
  'categorias.store': {
    methods: ["POST"],
    pattern: '/categorias',
    tokens: [{"old":"/categorias","type":0,"val":"categorias","end":""}],
    types: placeholder as Registry['categorias.store']['types'],
  },
  'categorias.show': {
    methods: ["GET","HEAD"],
    pattern: '/categorias/:id',
    tokens: [{"old":"/categorias/:id","type":0,"val":"categorias","end":""},{"old":"/categorias/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['categorias.show']['types'],
  },
  'categorias.update': {
    methods: ["PUT"],
    pattern: '/categorias/:id',
    tokens: [{"old":"/categorias/:id","type":0,"val":"categorias","end":""},{"old":"/categorias/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['categorias.update']['types'],
  },
  'categorias.destroy': {
    methods: ["DELETE"],
    pattern: '/categorias/:id',
    tokens: [{"old":"/categorias/:id","type":0,"val":"categorias","end":""},{"old":"/categorias/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['categorias.destroy']['types'],
  },
  'fincas.index': {
    methods: ["GET","HEAD"],
    pattern: '/fincas',
    tokens: [{"old":"/fincas","type":0,"val":"fincas","end":""}],
    types: placeholder as Registry['fincas.index']['types'],
  },
  'fincas.store': {
    methods: ["POST"],
    pattern: '/fincas',
    tokens: [{"old":"/fincas","type":0,"val":"fincas","end":""}],
    types: placeholder as Registry['fincas.store']['types'],
  },
  'fincas.show': {
    methods: ["GET","HEAD"],
    pattern: '/fincas/:id',
    tokens: [{"old":"/fincas/:id","type":0,"val":"fincas","end":""},{"old":"/fincas/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['fincas.show']['types'],
  },
  'fincas.update': {
    methods: ["PUT"],
    pattern: '/fincas/:id',
    tokens: [{"old":"/fincas/:id","type":0,"val":"fincas","end":""},{"old":"/fincas/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['fincas.update']['types'],
  },
  'fincas.destroy': {
    methods: ["DELETE"],
    pattern: '/fincas/:id',
    tokens: [{"old":"/fincas/:id","type":0,"val":"fincas","end":""},{"old":"/fincas/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['fincas.destroy']['types'],
  },
  'cultivos.index': {
    methods: ["GET","HEAD"],
    pattern: '/cultivos',
    tokens: [{"old":"/cultivos","type":0,"val":"cultivos","end":""}],
    types: placeholder as Registry['cultivos.index']['types'],
  },
  'cultivos.store': {
    methods: ["POST"],
    pattern: '/cultivos',
    tokens: [{"old":"/cultivos","type":0,"val":"cultivos","end":""}],
    types: placeholder as Registry['cultivos.store']['types'],
  },
  'cultivos.show': {
    methods: ["GET","HEAD"],
    pattern: '/cultivos/:id',
    tokens: [{"old":"/cultivos/:id","type":0,"val":"cultivos","end":""},{"old":"/cultivos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cultivos.show']['types'],
  },
  'cultivos.update': {
    methods: ["PUT"],
    pattern: '/cultivos/:id',
    tokens: [{"old":"/cultivos/:id","type":0,"val":"cultivos","end":""},{"old":"/cultivos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cultivos.update']['types'],
  },
  'cultivos.destroy': {
    methods: ["DELETE"],
    pattern: '/cultivos/:id',
    tokens: [{"old":"/cultivos/:id","type":0,"val":"cultivos","end":""},{"old":"/cultivos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cultivos.destroy']['types'],
  },
  'monitoreos.index': {
    methods: ["GET","HEAD"],
    pattern: '/monitoreos',
    tokens: [{"old":"/monitoreos","type":0,"val":"monitoreos","end":""}],
    types: placeholder as Registry['monitoreos.index']['types'],
  },
  'monitoreos.store': {
    methods: ["POST"],
    pattern: '/monitoreos',
    tokens: [{"old":"/monitoreos","type":0,"val":"monitoreos","end":""}],
    types: placeholder as Registry['monitoreos.store']['types'],
  },
  'monitoreos.show': {
    methods: ["GET","HEAD"],
    pattern: '/monitoreos/:id',
    tokens: [{"old":"/monitoreos/:id","type":0,"val":"monitoreos","end":""},{"old":"/monitoreos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['monitoreos.show']['types'],
  },
  'monitoreos.update': {
    methods: ["PUT"],
    pattern: '/monitoreos/:id',
    tokens: [{"old":"/monitoreos/:id","type":0,"val":"monitoreos","end":""},{"old":"/monitoreos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['monitoreos.update']['types'],
  },
  'monitoreos.destroy': {
    methods: ["DELETE"],
    pattern: '/monitoreos/:id',
    tokens: [{"old":"/monitoreos/:id","type":0,"val":"monitoreos","end":""},{"old":"/monitoreos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['monitoreos.destroy']['types'],
  },
  'recomendacion_tratamientos.index': {
    methods: ["GET","HEAD"],
    pattern: '/recomendacion_tratamientos',
    tokens: [{"old":"/recomendacion_tratamientos","type":0,"val":"recomendacion_tratamientos","end":""}],
    types: placeholder as Registry['recomendacion_tratamientos.index']['types'],
  },
  'recomendacion_tratamientos.store': {
    methods: ["POST"],
    pattern: '/recomendacion_tratamientos',
    tokens: [{"old":"/recomendacion_tratamientos","type":0,"val":"recomendacion_tratamientos","end":""}],
    types: placeholder as Registry['recomendacion_tratamientos.store']['types'],
  },
  'recomendacion_tratamientos.show': {
    methods: ["GET","HEAD"],
    pattern: '/recomendacion_tratamientos/:id',
    tokens: [{"old":"/recomendacion_tratamientos/:id","type":0,"val":"recomendacion_tratamientos","end":""},{"old":"/recomendacion_tratamientos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['recomendacion_tratamientos.show']['types'],
  },
  'recomendacion_tratamientos.update': {
    methods: ["PUT"],
    pattern: '/recomendacion_tratamientos/:id',
    tokens: [{"old":"/recomendacion_tratamientos/:id","type":0,"val":"recomendacion_tratamientos","end":""},{"old":"/recomendacion_tratamientos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['recomendacion_tratamientos.update']['types'],
  },
  'recomendacion_tratamientos.destroy': {
    methods: ["DELETE"],
    pattern: '/recomendacion_tratamientos/:id',
    tokens: [{"old":"/recomendacion_tratamientos/:id","type":0,"val":"recomendacion_tratamientos","end":""},{"old":"/recomendacion_tratamientos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['recomendacion_tratamientos.destroy']['types'],
  },
  'tratamientos.index': {
    methods: ["GET","HEAD"],
    pattern: '/tratamientos',
    tokens: [{"old":"/tratamientos","type":0,"val":"tratamientos","end":""}],
    types: placeholder as Registry['tratamientos.index']['types'],
  },
  'tratamientos.store': {
    methods: ["POST"],
    pattern: '/tratamientos',
    tokens: [{"old":"/tratamientos","type":0,"val":"tratamientos","end":""}],
    types: placeholder as Registry['tratamientos.store']['types'],
  },
  'tratamientos.show': {
    methods: ["GET","HEAD"],
    pattern: '/tratamientos/:id',
    tokens: [{"old":"/tratamientos/:id","type":0,"val":"tratamientos","end":""},{"old":"/tratamientos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['tratamientos.show']['types'],
  },
  'tratamientos.update': {
    methods: ["PUT"],
    pattern: '/tratamientos/:id',
    tokens: [{"old":"/tratamientos/:id","type":0,"val":"tratamientos","end":""},{"old":"/tratamientos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['tratamientos.update']['types'],
  },
  'tratamientos.destroy': {
    methods: ["DELETE"],
    pattern: '/tratamientos/:id',
    tokens: [{"old":"/tratamientos/:id","type":0,"val":"tratamientos","end":""},{"old":"/tratamientos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['tratamientos.destroy']['types'],
  },
  'aplicaciones_tratamientos.index': {
    methods: ["GET","HEAD"],
    pattern: '/aplicaciones_tratamientos',
    tokens: [{"old":"/aplicaciones_tratamientos","type":0,"val":"aplicaciones_tratamientos","end":""}],
    types: placeholder as Registry['aplicaciones_tratamientos.index']['types'],
  },
  'aplicaciones_tratamientos.store': {
    methods: ["POST"],
    pattern: '/aplicaciones_tratamientos',
    tokens: [{"old":"/aplicaciones_tratamientos","type":0,"val":"aplicaciones_tratamientos","end":""}],
    types: placeholder as Registry['aplicaciones_tratamientos.store']['types'],
  },
  'aplicaciones_tratamientos.show': {
    methods: ["GET","HEAD"],
    pattern: '/aplicaciones_tratamientos/:id',
    tokens: [{"old":"/aplicaciones_tratamientos/:id","type":0,"val":"aplicaciones_tratamientos","end":""},{"old":"/aplicaciones_tratamientos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['aplicaciones_tratamientos.show']['types'],
  },
  'aplicaciones_tratamientos.update': {
    methods: ["PUT"],
    pattern: '/aplicaciones_tratamientos/:id',
    tokens: [{"old":"/aplicaciones_tratamientos/:id","type":0,"val":"aplicaciones_tratamientos","end":""},{"old":"/aplicaciones_tratamientos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['aplicaciones_tratamientos.update']['types'],
  },
  'aplicaciones_tratamientos.destroy': {
    methods: ["DELETE"],
    pattern: '/aplicaciones_tratamientos/:id',
    tokens: [{"old":"/aplicaciones_tratamientos/:id","type":0,"val":"aplicaciones_tratamientos","end":""},{"old":"/aplicaciones_tratamientos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['aplicaciones_tratamientos.destroy']['types'],
  },
  'imagenes.index': {
    methods: ["GET","HEAD"],
    pattern: '/imagenes',
    tokens: [{"old":"/imagenes","type":0,"val":"imagenes","end":""}],
    types: placeholder as Registry['imagenes.index']['types'],
  },
  'imagenes.store': {
    methods: ["POST"],
    pattern: '/imagenes',
    tokens: [{"old":"/imagenes","type":0,"val":"imagenes","end":""}],
    types: placeholder as Registry['imagenes.store']['types'],
  },
  'imagenes.show': {
    methods: ["GET","HEAD"],
    pattern: '/imagenes/:id',
    tokens: [{"old":"/imagenes/:id","type":0,"val":"imagenes","end":""},{"old":"/imagenes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['imagenes.show']['types'],
  },
  'imagenes.update': {
    methods: ["PUT"],
    pattern: '/imagenes/:id',
    tokens: [{"old":"/imagenes/:id","type":0,"val":"imagenes","end":""},{"old":"/imagenes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['imagenes.update']['types'],
  },
  'imagenes.destroy': {
    methods: ["DELETE"],
    pattern: '/imagenes/:id',
    tokens: [{"old":"/imagenes/:id","type":0,"val":"imagenes","end":""},{"old":"/imagenes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['imagenes.destroy']['types'],
  },
  'analisis_ia.index': {
    methods: ["GET","HEAD"],
    pattern: '/analisis_ia',
    tokens: [{"old":"/analisis_ia","type":0,"val":"analisis_ia","end":""}],
    types: placeholder as Registry['analisis_ia.index']['types'],
  },
  'analisis_ia.store': {
    methods: ["POST"],
    pattern: '/analisis_ia',
    tokens: [{"old":"/analisis_ia","type":0,"val":"analisis_ia","end":""}],
    types: placeholder as Registry['analisis_ia.store']['types'],
  },
  'analisis_ia.show': {
    methods: ["GET","HEAD"],
    pattern: '/analisis_ia/:id',
    tokens: [{"old":"/analisis_ia/:id","type":0,"val":"analisis_ia","end":""},{"old":"/analisis_ia/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['analisis_ia.show']['types'],
  },
  'analisis_ia.update': {
    methods: ["PUT"],
    pattern: '/analisis_ia/:id',
    tokens: [{"old":"/analisis_ia/:id","type":0,"val":"analisis_ia","end":""},{"old":"/analisis_ia/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['analisis_ia.update']['types'],
  },
  'analisis_ia.destroy': {
    methods: ["DELETE"],
    pattern: '/analisis_ia/:id',
    tokens: [{"old":"/analisis_ia/:id","type":0,"val":"analisis_ia","end":""},{"old":"/analisis_ia/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['analisis_ia.destroy']['types'],
  },
  'recomendaciones.index': {
    methods: ["GET","HEAD"],
    pattern: '/recomendaciones',
    tokens: [{"old":"/recomendaciones","type":0,"val":"recomendaciones","end":""}],
    types: placeholder as Registry['recomendaciones.index']['types'],
  },
  'recomendaciones.store': {
    methods: ["POST"],
    pattern: '/recomendaciones',
    tokens: [{"old":"/recomendaciones","type":0,"val":"recomendaciones","end":""}],
    types: placeholder as Registry['recomendaciones.store']['types'],
  },
  'recomendaciones.show': {
    methods: ["GET","HEAD"],
    pattern: '/recomendaciones/:id',
    tokens: [{"old":"/recomendaciones/:id","type":0,"val":"recomendaciones","end":""},{"old":"/recomendaciones/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['recomendaciones.show']['types'],
  },
  'recomendaciones.update': {
    methods: ["PUT"],
    pattern: '/recomendaciones/:id',
    tokens: [{"old":"/recomendaciones/:id","type":0,"val":"recomendaciones","end":""},{"old":"/recomendaciones/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['recomendaciones.update']['types'],
  },
  'recomendaciones.destroy': {
    methods: ["DELETE"],
    pattern: '/recomendaciones/:id',
    tokens: [{"old":"/recomendaciones/:id","type":0,"val":"recomendaciones","end":""},{"old":"/recomendaciones/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['recomendaciones.destroy']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
